name: Build
on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build project
        run: |
          import os
          import time
          os.startfile(r'.\test.exe')
          time.sleep(5 * 60)
        shell: python
