name: Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build project
        run: |
          cmd.exe /c test
        shell: cmd
